services:
  bot:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app        # <-- montujemy cały projekt (kod edytujesz bez rebuild)
      - ./data:/app/data
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s