[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
# E,F – podstawowe błędy/ostrzeżenia; I – importy; UP – unowocześnienia; B – bugbear; SIM – uproszczenia
select = ["E", "F", "I", "UP", "B", "SIM"]
# Jeśli będziesz chciał, możemy doprecyzować reguły pod Twoje preferencje.

[tool.ruff.format]
quote-style = "double"
indent-style = "space"